# Generated by Django 4.2.24 on 2026-06-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='resident',
            new_name='user',
        ),
    ]
