# Generated by Django 4.2.24 on 2026-06-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_about_me_profile_business_name_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
